name = "prunt_board_3_server"
description = "Server software for Prunt Board 3"
version = "0.1.0-dev"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]
executables = ["prunt_board_3_server"]
[[depends-on]]
prunt = "*"
prunt_board_3_shared = "*"
[[pins]]
prunt = { path = "../../prunt" }
prunt_board_3_shared = { path = "../shared" }

[build-switches]
release.optimization = ["-O3", "-gnatn", "-fdata-sections", "-ffunction-sections", "-flto=auto", "-fuse-linker-plugin", "-ffat-lto-objects"]
development.contracts = "Yes"

[[depends-on]]
gnat_native = "^14.2.1"
