name = "prunt_board_3_firmware"
description = ""
version = "0.1.0-dev"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

[[depends-on]]
gnat_arm_elf = "^14.2.1"
prunt_board_3_shared = "*"
[[pins]]
prunt_board_3_shared = { path = "../shared" }
